# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 16:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateField(default=datetime.date(2016, 10, 16)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_montant',
            field=models.FloatField(),
        ),
    ]
