# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 16:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0002_auto_20161016_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateField(default=datetime.datetime(2016, 10, 16, 16, 38, 11, 787000, tzinfo=utc)),
        ),
    ]
