# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 16:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0004_auto_20161016_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateField(verbose_name=datetime.datetime(2016, 10, 16, 16, 42, 20, 61000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_montant',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
