# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 14:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0005_auto_20161016_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etablissement',
            name='etablissement_nom',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateField(default=datetime.date(2016, 11, 12)),
        ),
    ]
