# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0006_auto_20161112_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etablissement',
            name='etablissement_nom',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
