# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-17 20:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0007_auto_20161112_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametre_nom', models.CharField(db_index=True, max_length=100, unique=True)),
                ('parametre_montant', models.DecimalField(decimal_places=2, max_digits=5)),
                ('parametre_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='depenses.Categorie')),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateField(default=datetime.date(2016, 12, 17)),
        ),
    ]
