# Generated by Django 2.0.5 on 2018-05-07 23:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0009_auto_20161217_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='categorie_objectif',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateField(default=datetime.date(2018, 5, 8)),
        ),
    ]
