# Generated by Django 2.0.5 on 2018-05-07 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0010_auto_20180508_0117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='categorie_objectif',
        ),
    ]
