# Generated by Django 2.0.5 on 2018-05-08 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0011_remove_categorie_categorie_objectif'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parametre',
            old_name='parametre_montant',
            new_name='parametre_montant_hebdo',
        ),
    ]
